#======================= BASIC PACKAGES ============================
- name: update apt list
  apt:
    update_cache: yes

- name: Install basic packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - python3
      - python3-pip
    state: present

#======================= GPG KEYS ============================


- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

#======================= ADD REPOS ============================

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable'
    state: present
    update_cache: yes

#======================= INSTALL ADDITIONAL PACKAGES ============================

- name: Install additional packages
  ansible.builtin.apt:
    name:
      - libc6
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true


- name: Install docker python packages
  ansible.builtin.pip:
    name:
      - docker==6.1.3.
      - docker-compose==1.29.2
      - requests==2.28.1
      - urllib3==1.26.18

##======================= DOCKER ============================


- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
