
---
- name: "Installing Docker and docker compose"
  hosts: all
  roles:
  - docker-install

- name: "Run Docker compose service: database"
  hosts: db_server
  vars_files:
    - "./docker-service/vars/database.yml"
  roles:
  - docker-service

- name: "Run Docker compose service: web app"
  hosts: todo
  vars_files:
    - "./docker-service/vars/webapp.yml"
  roles:
  - docker-service
