---

docker_service__compose:
  version: "3"

  services:
    app:
      image: antonaleks/101-todo-app
      restart: on-failure
      ports:
        - "80:80"
      environment:
        MYSQL_HOST: localhost
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
        MYSQL_DB: todos